### ISSUE TITLE
Add declaration for OpenTermsArchive service

### ISSUE THREAD

**Issue by martinratinaud** [OpenTermsArchive/template-declarations#1]
In order for tests not to fail

- [ ] Add `OpenTermsArchive.json` with `Privacy Policy`
- [ ] remove `OpenTermsArchive.json` in `init.sh`
- [ ] Complete doc if needed

**Comment by martinratinaud** [comment]
@MattiSG, can you please tell Emmanuel

**Comment by Manu1400** [comment]
@martinratinaud : https://github.com/OpenTermsArchive/template-declarations/pull/5

**Comment by MattiSG** [comment]
Done in https://github.com/OpenTermsArchive/template-declarations/pull/5.
