### ISSUE TITLE
Lint declarations in CI

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/template-declarations#13]
Currently, the only checks that are made in CI in declarations repositories are schema validation and testing. Linting is not executed in CI while it should be, as a dedicated job.

Reported by @Kissaki in https://github.com/OpenTermsArchive/contrib-declarations/pull/696#issuecomment-1298347834

**Comment by MattiSG** [comment]
@martinratinaud this seems relevant to implement as part of your intervention on every collection to update the deployment process 🙂

**Comment by martinratinaud** [comment]
I agree @MattiSG but let's do this in another PR than [this one](https://github.com/OpenTermsArchive/contrib-declarations/pull/748) as I don't know yet if you wish the script to lint and commit or just to throw an error.
If lint should commit also, I will have to check how @Ndpnt did for the release process.

**Comment by MattiSG** [comment]
By “linting” I really mean just checking that the rules are respected and enforcing them by blocking, not auto fixing since not all problems can be auto fixed anyway 🙂

**Comment by martinratinaud** [comment]
After discussion with @Ndpnt and @clementbiron. We all think it would be better to auto lint and make a lint commit directly on the server.

Here are some pros
- Any contributor that contributes directly on GitHub (for a small fix for example)
- Any contributor not willing to install the whole stack and just creates a JSON file and pushes it
- Any contributor that forgot to run `npm run lint`

Moreover, the eslint normal format is usually not very readable when linting JSON file so it would have to be tweaked.

I suggest we implement
- a new worklow `lint`
- in case a file is linted, commit it as Github User and push it to the repo before deploying

**Comment by clementbiron** [comment]
I agree with the auto lint in CI but the user must be told :
- what is happening and why
- what they can do if the auto lint is not working

**Comment by MattiSG** [comment]
Sure, if you have resources to make the autofix process work, that sounds like a cool addition. I am not arguing its value, I am simply saying that what is important is that we lint in CI so that misformatted declarations are caught early on. Autofix is two orders of magnitude more complex for limited added value. This issue that I created is fulfilled by linting declarations in CI. It does not need to include autofix to be fulfilled.

**Comment by martinratinaud** [comment]
Ok, After investigation, linting was test but as part of `ota validate`, which is a bit weird.

I proposed the [following PR](https://github.com/ambanum/OpenTermsArchive/pull/991) to split it correctly along with a [PR on collection](https://github.com/OpenTermsArchive/sandbox-declarations/pull/175/files).
