### ISSUE TITLE
Run CI for pull requests from forks

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/template-declarations#14]
Pull requests from forks currently don't trigger CI, meaning that external contributors do not benefit from automated feedback and that maintainers need to manually trigger a build by pushing to a local branch. The contribution workflow would be simpler and more effective if jobs were run from forks.

Examples: https://github.com/OpenTermsArchive/contrib-declarations/pull/701, https://github.com/OpenTermsArchive/contrib-declarations/pull/695

**Comment by Ndpnt** [comment]
See https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Comment by MattiSG** [comment]
Thanks to the documentation provided above, this thus seems to be a GitHub Actions settings choice done through the UI. For example, for [contrib-declarations](https://github.com/OpenTermsArchive/contrib-declarations/settings/actions).

This issue would thus be implemented by adding documentation on recommended settings in the template README.
