### ISSUE TITLE
Install Open Terms Archive engine as a dependency

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/template-declarations#15]
Install the Open Terms Archive engine as a dependency through NPM. This will make declarations runnable without needing an external global executable, and will add versioning support for the engine, enabling deploying breaking changes without breaking unmaintained instances.

Depends on https://github.com/ambanum/OpenTermsArchive/pull/957.

**Comment by MattiSG** [comment]
@Ndpnt hasn't this been done already? 🙂 I'll let you either close this issue or assign @martinratinaud if this is now about ensuring every instance follows this pattern.

**Comment by martinratinaud** [comment]
This is done in #18. Will close after merge
