### ISSUE TITLE
Document available `npm` commands

### ISSUE THREAD

**Issue by Ndpnt** [OpenTermsArchive/template-declarations#6]
Documentation for available `npm` commands (`test`, `test:schema`, …) should be added in the declarations repositories README.

**Comment by martinratinaud** [comment]
It is actually in the CONTRIBUTION guide of contrib-declarations
If we do not hold this in a common repo, everytime we add a new feature/script, this readme will be obsolete for all repos.

Thus I suggest to NOT hold it inside the template

For now I've added it here https://github.com/OpenTermsArchive/contrib-declarations/pull/565/commits/80554e50c4e30b86a003b4d4004e06b0fe1fc48e.

**Comment by MattiSG** [comment]
I fail to understand why `contrib-declarations` is more of a “common repo” than `template-declarations` 🤔

**Comment by martinratinaud** [comment]
@MattiSG, well fail not as It's not more common.
It's just that today, the contribution guide happens to be in the contrib so I just modified it.

I can definitely move it at the root of this repo but maybe in another PR than the one for linting.
For this we will also need to modify all template children link to the contribution guide.
Will do so right after merging this one

**Comment by MattiSG** [comment]
Ah okay, I probably misunderstood “Thus I suggest to NOT hold it inside the template”. I understand that you suggest this _in the current context_ when the documentation is in the CONTRIBUTING of `contrib`, not that you oppose _migrating_ it to `template`. If that is correct, then I agree with you 🙂

**Comment by martinratinaud** [comment]
Sure.

I think we can plan in the next sprint to migrate this CONTRIBUTING at the root of `template-declarations`.
